### PR TITLE
Requirements updated to latest non eol version

### PR DESCRIPTION
**Pull request by andre-m-dev**
https://endoflife.date/rails -> 6.1
https://endoflife.date/ruby -> 3.1

### CODE REVIEW

**Comment by tobischo** [comment]
I appreciate the pull request, but unless there is a strong reason for you to require it to be on latest end of life level for everything, I would rather allow it to be usable in more places that might not be as easily updatable.

**Comment by andre-m-dev** [comment]
More for regulatory reasons. I would force people a little, but yes, I understand the objection. Otherwise, feel free to close

**Comment by tobischo** [comment]
Can you elaborate on the regulation that forces dependencies to only be allowed to run on actively supported versions of related software?

I would assume that that would be very difficult and the important part is that you are running everything in sufficiently new?

**Comment by andre-m-dev** [comment]
I don't know whether there are any direct legal requirements in this regard. On the other hand, if an incident or audit reveals that "outdated" software with known safety gaps has been used, there will certainly be problems. But as I said, otherwise feel free to close this.

**Comment by tobischo** [comment]
Alright, closing this for now.

Eventually this will be updated, but as of right now, I don't see the necessity to make it harder for people to use.

It works perfectly fine with latest activerecord and latest ruby.
Everyone can use the latest version, but ultimately I would rather people are able to install updates for this library if there is a bug than to force a decision.
Anyone with a compliance need to have their libraries and ruby runtime updated can do so without being blocked by sps_king.

The relevant bit would be to update it, if we wanted to use a dependency or a language feature which is not usable in older ruby and therefore might have a misleading labeling of compatibility. At this point it costs us nothing to provide the flexibility.

**Pull request closed without merging**
